### Get CLI arguments
#
ARG base_image_tag



### Define base image
#
FROM centos:$base_image_tag



### Install
#
RUN yum update -y
RUN yum install -y curl wget
RUN yum install -y bzip2 gzip tar unzip xz zip
RUN yum install -y git
RUN yum install -y autoconf automake gcc gcc-c++ libtool m4 make
