name: 'Publish - AlmaLinux - C'



on:
  pull_request:
    branches:
      - master
    paths:
      - '.github/workflows/publish-almalinux-ci-c'
      - 'Dockerfile-almalinux-ci-c'

  push:
    branches:
      - master
    paths:
      - '.github/workflows/publish-almalinux-ci-c'
      - 'Dockerfile-almalinux-ci-c'

  schedule:
    - cron: '12 5 * * 0'

  workflow_dispatch:



jobs:
  publish-almalinux-c:



    strategy:
      matrix:
        base_image_tag:
          - '8-base:latest'
          - '9-base:latest'

        include:
          - base_image_tag: '8-base:latest'
            publish_repotags: |
              ciready/almalinux:8-ci-c

          - base_image_tag: '9-base:latest'
            publish_repotags: |
              ciready/almalinux:9-ci-c
              ciready/almalinux:latest-ci-c



    name: 'Publish - almalinux:${{matrix.base_image_tag}}'
    runs-on: ubuntu-latest
    steps:


      - name: 'Check out the code'
        uses: actions/checkout@v2
        with:
          fetch-depth: 0


      - name: 'Set up Docker Buildx'
        uses: docker/setup-buildx-action@v1


      - name: 'Login to DockerHub'
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}


      - name: 'Build and push'
        uses: docker/build-push-action@v2
        with:
          build-args: |
            base_image_tag=${{matrix.base_image_tag}}
          context: .
          file: ./Dockerfile-almalinux-ci-c
          platforms: linux/amd64
          push: true
          tags: ${{ matrix.publish_repotags }}
