name: 'Publish - OpenSUSE - C'



on:
  pull_request:
    branches:
      - master
    paths:
      - '.github/workflows/publish-opensuse-ci-c'
      - 'Dockerfile-opensuse-ci-c'

  push:
    branches:
      - master
    paths:
      - '.github/workflows/publish-opensuse-ci-c'
      - 'Dockerfile-opensuse-ci-c'

  schedule:
    - cron: '14 5 * * 0'

  workflow_dispatch:



jobs:
  publish-opensuse-c:



    strategy:
      matrix:
        base_image_repotag:
          - 'opensuse/leap:15.5'
          - 'opensuse/leap:15.6'
          - 'opensuse/tumbleweed:latest'

        include:
          - base_image_repotag: 'opensuse/leap:15.5'
            publish_repotags: |
              ciready/opensuse:leap-15.5-ci-c

          - base_image_repotag: 'opensuse/leap:15.6'
            publish_repotags: |
              ciready/opensuse:leap-15.6-ci-c
              ciready/opensuse:leap-latest

          - base_image_repotag: 'opensuse/tumbleweed:latest'
            publish_repotags: |
              ciready/opensuse:tumbleweed-latest-ci-c



    name: 'Publish - ${{matrix.base_image_repotag}}'
    runs-on: ubuntu-latest
    steps:


      - name: 'Check out the code'
        uses: actions/checkout@v2
        with:
          fetch-depth: 0


      - name: 'Set up Docker Buildx'
        uses: docker/setup-buildx-action@v1


      - name: 'Login to DockerHub'
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}


      - name: 'Build and push'
        uses: docker/build-push-action@v2
        with:
          build-args: |
            base_image_repotag=${{matrix.base_image_repotag}}
          context: .
          file: ./Dockerfile-opensuse-ci-c
          platforms: linux/amd64
          push: true
          tags: ${{ matrix.publish_repotags }}
