name: 'Publish - Alpine - CI-C'



on:
  pull_request:
    branches:
      - master
    paths:
      - '.github/workflows/publish-alpine-ci-c'
      - 'Dockerfile-alpine-ci-c'

  push:
    branches:
      - master
    paths:
      - '.github/workflows/publish-alpine-ci-c'
      - 'Dockerfile-alpine-ci-c'

  schedule:
    - cron: '12 5 * * 0'

  workflow_dispatch:



jobs:
  publish-alpine-c:



    strategy:
      matrix:
        base_image_tag:
          - '3.14'
          - '3.15'
          - '3.16'

        include:
          - base_image_tag: '3.14'
            publish_repotags: |
              ciready/alpine:3.14-ci-c

          - base_image_tag: '3.15'
            publish_repotags: |
              ciready/alpine:3.15-ci-c

          - base_image_tag: '3.16'
            publish_repotags: |
              ciready/alpine:3.16-ci-c
              ciready/alpine:latest-ci-c



    name: 'Publish - alpine:${{matrix.base_image_tag}}'
    runs-on: ubuntu-latest
    steps:


      - name: 'Check out the code'
        uses: actions/checkout@v2
        with:
          fetch-depth: 0


      - name: 'Set up Docker Buildx'
        uses: docker/setup-buildx-action@v1


      - name: 'Login to DockerHub'
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}


      - name: 'Build and push'
        uses: docker/build-push-action@v2
        with:
          build-args: |
            base_image_tag=${{matrix.base_image_tag}}
          context: .
          file: ./Dockerfile-alpine-ci-c
          platforms: linux/amd64
          push: true
          tags: ${{ matrix.publish_repotags }}
