name: 'Publish - ArchLinux - C'



on:
  pull_request:
    branches:
      - master
    paths-ignore:
      - '.github/*.md'
      - '.github/workflows/**'
      - '.gitignore'
      - 'LICENSE'
      - 'README.md'

  push:
    branches:
      - master
    paths-ignore:
      - '.github/*.md'
      - '.github/workflows/**'
      - '.gitignore'
      - 'LICENSE'
      - 'README.md'

  schedule:
    - cron: '43 5 * * 0'

  workflow_dispatch:



jobs:
  publish-archlinux-c:



    strategy:
      matrix:
        base_image_tag:
          - 'base-devel'

        include:
          - base_image_tag: 'base-devel'
            publish_repotags: |
              ciready/archlinux:base-devel-ci-c



    name: 'Publish - archlinux:${{matrix.base_image_tag}}'
    runs-on: ubuntu-latest
    steps:


      - name: 'Check out the code'
        uses: actions/checkout@v2
        with:
          fetch-depth: 0


      - name: 'Set up Docker Buildx'
        uses: docker/setup-buildx-action@v1


      - name: 'Login to DockerHub'
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}


      - name: 'Build and push'
        uses: docker/build-push-action@v2
        with:
          build-args: |
            base_image_tag=${{matrix.base_image_tag}}
          context: .
          file: ./Dockerfile-archlinux-ci-c
          platforms: linux/amd64
          push: true
          tags: ${{ matrix.publish_repotags }}
