name: 'Publish - Debian - C'



on:
  pull_request:
    branches:
      - master
    paths:
      - '.github/workflows/publish-debian-ci-c'
      - 'Dockerfile-debian-ci-c'

  push:
    branches:
      - master
    paths:
      - '.github/workflows/publish-debian-ci-c'
      - 'Dockerfile-debian-ci-c'

  schedule:
    - cron: '13 5 * * 0'

  workflow_dispatch:



jobs:
  publish-debian-c:



    strategy:
      matrix:
        base_image_tag:
          - 'buster'
          - 'bullseye'
          - 'bookworm'
          - 'sid'

        include:
          - base_image_tag: 'buster'
            publish_repotags: |
              ciready/debian:buster-ci-c
              ciready/debian:10-ci-c
              ciready/debian:oldstable-ci-c

          - base_image_tag: 'bullseye'
            publish_repotags: |
              ciready/debian:bullseye-ci-c
              ciready/debian:11-ci-c
              ciready/debian:stable-ci-c
              ciready/debian:latest-ci-c

          - base_image_tag: 'bookworm'
            publish_repotags: |
              ciready/debian:bookworm-ci-c
              ciready/debian:12-ci-c
              ciready/debian:testing-ci-c

          - base_image_tag: 'sid'
            publish_repotags: |
              ciready/debian:sid-ci-c



    name: 'Publish - debian:${{matrix.base_image_tag}}'
    runs-on: ubuntu-latest
    steps:


      - name: 'Check out the code'
        uses: actions/checkout@v2
        with:
          fetch-depth: 0


      - name: 'Set up Docker Buildx'
        uses: docker/setup-buildx-action@v1


      - name: 'Login to DockerHub'
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}


      - name: 'Build and push'
        uses: docker/build-push-action@v2
        with:
          build-args: |
            base_image_tag=${{matrix.base_image_tag}}
          context: .
          file: ./Dockerfile-debian-ci-c
          platforms: linux/amd64
          push: true
          tags: ${{ matrix.publish_repotags }}
